### ISSUE TITLE
What if I only have hand 2D keypints

### ISSUE THREAD

**Issue by quyanqiu** [vchoutas/expose#1]
Hi,Thanks for the nice work of NETWORK version of smplx,I have been watching this serials of project for so long.
Hey here is a issue here, If I only have hand label(left/hand) and hand 2D keypoints,Can we just fit the hand part of your network to a hand-only image and get hand parameters (s,R,t and MANO parameters)?

**Comment by vchoutas** [comment]
In principle yes, but we currently do not provide a hand-only demo.

**Comment by quyanqiu** [comment]
yes，It seem that this is what your hand_predictor doing right now.
 I test some hard case where your original optimized based smplx-method can not work,And the result is acceptable。
I would like to change some part of your code of hand_predictor.py to get a fairy well initialize value of a single hand mano parameter, Then doing optimized based method to finetune those result.
Anyway,Thx for your great work。

**Comment by hungsing92** [comment]
@quyanqiu Hi, I also want to check the performance of the hand model, can you share your hand-only demo? 1695979109@qq.com. Thanks!!!
