### ISSUE TITLE
Cannot find "smplx_flip_correspondences.npz"

### ISSUE THREAD

**Issue by JiahaoPlus** [vchoutas/expose#11]
Hello, in "curated_fittings.py", variable "vertex_flip_correspondences" needs "**data/smplx_flip_correspondences.npz**" file, but I cannot find it in the folder. What does it use for? If possible, could you please upload it? Thanks!

**Comment by vchoutas** [comment]
This file can be found in the  [download section of SMPL-X](https://smpl-x.is.tue.mpg.de/downloads).
