### ISSUE TITLE
Number of smpl params?

### ISSUE THREAD

**Issue by ortegatron** [vchoutas/expose#15]
Hi, I'm trying to use VPoser to encode the generated SMPL pose from an image.

As far as I've seen Vposer uses a 63  (21*3) length vector (the smpl vector?) to encode it to a vector on its latent space (32 length).
But using expose, the closest to a smpl vector I can get is in: model_output.get('body')["final"]["body_pose"], which is a (1,21,3,3) vector.  so it has 3 times more params than vposer is expecting.

What is the reason for this? 
Thank you!

**Comment by ortegatron** [comment]
Update: Seems like expose is expressing each pose keypoint on a 6-dim space, as said on section 3.1 of the original paper.
I will try now to convert this 6-space rotation into 3-space (angles)

**Comment by vchoutas** [comment]
The returned parameters are rotation matrices, hence the 3 by 3 size. To encode it to a VPoser latent space you will need to convert the 21 rotation matrices to axis angle.

**Comment by ortegatron** [comment]
Thanks for the reply.
I'm trying to do matrix_to_euler_angles from (https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html)
It should be converting the 3x3 rotation matrix to euler angle, ready to use with VPoser. But it's not working properly.
Am I using the wrong conversion? Thanks again!

**Comment by vchoutas** [comment]
@ortegatron VPoser expects the axis angle representation, not euler angles. 
So, you should be using [the SO3 log map](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.so3_log_map) from pytorch3d. 
We also provide an implementation for rotation matrix to axis-angle [here](https://github.com/vchoutas/expose/blob/dffc38d62ad3817481d15fe509a93c2bb606cb8b/expose/utils/rotation_utils.py#L55).

**Comment by ortegatron** [comment]
Worked! I ended up using that function on the expose utils. 
Thank you very much for taking your time to reply, very appreciated.
