### ISSUE TITLE
how did you get the GT data from EHF??

### ISSUE THREAD

**Issue by sunwonlikeyou** [vchoutas/expose#17]
In EHF.zip
there are 
- filename: "*_img.jpg"    - RGB full-body image in JPG format.
- filename: "*_img.png"    - RGB full-body image in PNG format.
- filename: "*_scan.obj"   - 3D scan for this frame (multi-view stereo reconstruction).
- filename: "*_align.ply"  - Alignment of SMPL-X to the 3D scan, in the form of a 3D mesh (used as pseudo ground truth).
- filename: "*_2Djnt.json" - 2D joints estimated with OpenPose (from monocular RGB).
- filename: "*_2Djnt.png"  - Visualization of OpenPose 2D joints.

also the length of 'v'(means vertices) is 128343 and
length of 'f'(means faces) is 255832..

how did you preprocess the EHF??

**Comment by vchoutas** [comment]
@sunwonlikeyou What gt data are you referring to? The number of vertices you mention is probably the one from the scan, not the registration. All registration, i.e. ply files, have the SMPL-X topology.

**Comment by sunwonlikeyou** [comment]
sorry.. 
i did it 
Thank you
