### ISSUE TITLE
how to translate the smplx param to smpl

### ISSUE THREAD

**Issue by tomyjack** [vchoutas/expose#18]
first thanks for your greate work!
like the title show, i use the expose result to the smpl lib, after i slove the pose and betas ,the trans params is confuse me.
what is the trans in smpl equal to smplx??
thanks

**Comment by vchoutas** [comment]
The SMPL and SMPL-X shape spaces are not compatible, you can't use betas from SMPL for SMPL-X and vice versa. 
trans is a translation parameter. What would you like to do?
From ExPose, you could use the estimate translation used for rendering, i.e. transl.

**Comment by tomyjack** [comment]
@vchoutas thanks!
i want to use the expose output param to construct the SMPL model, because another project is use SMPL, the shape betas is diffent, but i just need similar shape, so that is ok for me.
for example , [tailornet ](https://github.com/chaitanya100100/TailorNet)is use SMPL, and i want to put the expose model to tailornet, and let it move!!
thanks!

**Comment by vchoutas** [comment]
@tomyjack We have added code to the SMPL-X repository that transfers the parameters of one model to another.

**Comment by tomyjack** [comment]
@vchoutas thanks!!!
