### ISSUE TITLE
Bent knees of reconstructed model

### ISSUE THREAD

**Issue by farazBhatti** [vchoutas/expose#27]
Reconstructed 3d model has bent knees, although person in image is standing straight.Any ideas?
Meshlab is used for visualization of model 

![Screenshot from 2020-12-14 13-58-27](https://user-images.githubusercontent.com/37732181/102060922-98dfbd80-3e14-11eb-883a-b7c09b182bc9.png)

**Comment by ankitsharma07** [comment]
I have the same problem, although, in a similar solution called HMR which used to make a mesh from SMPL, I multiplied the poses with keypoints detected from openpose that made it straight.

**Comment by ankitsharma07** [comment]
@farazBhatti Were you able to straighten the mesh?

**Comment by farazBhatti** [comment]
i didn't tried the solution you gave. if you have applied it should work for me as well. At the moment i am trying to figure out which one these model would best suit for fat person. Thats why i closed it

**Comment by akchain** [comment]
do you solve the problem?

**Comment by ankitsharma07** [comment]
@akchain No, I haven't yet. I would like to know the solution if you find one.
