### ISSUE TITLE
Bent knees of reconstructed model!!!

### ISSUE THREAD

**Issue by Tanupvats** [vchoutas/expose#31]
Reconstructed 3d model has bent knees, although the person in the image is standing straight.
Can anyone tell why this is happening???

**Comment by Anirudh257** [comment]
@Tanupvats Can you post your input image? Is it having occlusion?

**Comment by Tanupvats** [comment]
![bent_knee](https://user-images.githubusercontent.com/61944951/105661816-5968be80-5ef4-11eb-863b-d5fd1b1965b6.png)
sorry for replying late @Anirudh257 and thanks for asking.

**Comment by Anirudh257** [comment]
@Tanupvats No problem. Can you also post the *RGB* image on which you have run SMPL-X on?

**Comment by Tanupvats** [comment]
@Anirudh257 ya sure! here is the image
![calibresult3](https://user-images.githubusercontent.com/61944951/105851587-4c89bf00-6009-11eb-94ed-0bc4a2d583c0.jpg)

**Comment by Anirudh257** [comment]
I am able to get a proper image with the knees straight. 

![image](https://user-images.githubusercontent.com/16001446/105890526-7eb11600-6035-11eb-8524-6be38acde1c5.png)

What were your hyperparameters? These are the parameters that I used:

`python3 smplifyx/main.py --config cfg_files/fit_smplx.yaml --data_folder data_folder_check/ --output_folder output_folder_check/ --visualize=False --model_folder model_folder/models/ --vposer_ckpt vposer_folder/vposer_v1_0/ --interpenetration False --focal_length 1500
`

**Comment by Tanupvats** [comment]
@Anirudh257  actually I tried to run the image on the Inference.py file they have provided and used the same parameters as they did. I am a new bee in this field and I don't
have much knowledge about this. so could you please give me instruction or some sort of follow up path to achieve this result?.
And Thank you so much for replying.

**Comment by Anirudh257** [comment]
@Tanupvats My bad!! I used https://github.com/vchoutas/smplify-x/ to run the code. You can check it out once. Follow the instructions as given by the authors on their GitHub repository and you will get the result. Do extract the openpose keypoints as well.

**Comment by Tanupvats** [comment]
```
Processing: DATA_FOLDER/images/calibresult3.jpg
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "/content/smplify-x/smplifyx/fit_single_frame.py", line 188, in fit_single_frame
    vposer, _ = load_vposer(vposer_ckpt, vp_model='snapshot')
  File "/content/smplify-x/src/human-body-prior/human_body_prior/tools/model_loader.py", line 56, in load_vposer
    ps, trained_model_fname = expid2model(expr_dir)
  File "/content/smplify-x/src/human-body-prior/human_body_prior/tools/model_loader.py", line 31, in expid2model
    best_model_fname = sorted(glob.glob(os.path.join(expr_dir, 'snapshots', '*.pt')), key=os.path.getmtime)[-1]
IndexError: list index out of range
```
@Anirudh257 thank you but I got this error while trying to run the smplify-x. if it isn't bothering can you give a solution to this?

**Comment by Tanupvats** [comment]
hi, @Anirudh257 I managed to run get the results using the same parameters as you did but I got this.
![2021-01-28 (2)](https://user-images.githubusercontent.com/61944951/106097624-a7ccc600-615d-11eb-83ba-f4835fd024b9.png)
could you tell me why this is happening?

**Comment by Anirudh257** [comment]
It doesn't have bent knees. It seems to be correct. What is the exact issue?

**Comment by Tanupvats** [comment]
@Anirudh257 I mean it's tilted towards its front while the person is standing straight.

**Comment by Anirudh257** [comment]
Okay, I am not so sure, but you can try changing the focal length parameters and other parameters. If you feel that the results don't improve, try using https://github.com/ahmedosman/STAR, https://github.com/vchoutas/smplify-x or other SMPL-X variants.
