### ISSUE TITLE
Value Error in openpoose utils when empty frames encountered

### ISSUE THREAD

**Issue by GIMPS** [vchoutas/expose#4]
`ValueError: need at least one array to stack` is raised by Numpy in [data/utils/keypoints.py#L59](https://github.com/vchoutas/expose/blob/e4de58f529c79e7581f211056168548d3b044509/expose/data/utils/keypoints.py#L59), when an empty frame is encountered (i.e., no person detected). The issue can be solved by switching the orders of line 59 and line 60 in keypoint.py. Please kindly have a look @vchoutas.

**Comment by vchoutas** [comment]
@GIMPS Thanks for the suggestion, I will push this now.
