### ISSUE TITLE
Why out_img shape is (4,y,x) and rgb error in out_img['rgb'][idx]

### ISSUE THREAD

**Issue by codeHorasan** [vchoutas/expose#58]
I am getting 'rgb' error in `out_img['rgb'][idx]`, I had to comment out that line. `out_img['hd_orig_overlay'][idx]` and `out_img['hd_overlay'][idx]` have shape of (4,y,x), I transposed it but I don't understand why it has shape of 4 instead of 3. I also cannot save the image due to this reason but plot it.

**Comment by yyyqwq** [comment]
@codeHorasan
How to solve it, bro? Just comment this line ?
