### ISSUE TITLE
Generate Famale / Male meshes

### ISSUE THREAD

**Issue by MistreanuIonutCosmin** [vchoutas/expose#8]
Hello and thank you for this awesome work!

Can you please tell me if it's possible to generate models that use male or female shapes? I tried enforcing this through SMPLX_FEMALE.pkl and SMPLX_FEMALE.npz files but it still generated neutral meshes.

Best regards!

**Comment by vchoutas** [comment]
Unfortunately you cannot swap out the models. The neutral, female and male shape spaces of SMPL-X are not compatible. Simply swapping out the models will not give you what you want, you have to re-train from scratch.

**Comment by Tetsujinfr** [comment]
@vchoutas sorry, that means that the female or male model do not work with this code? only the neutral model works?
thanks

**Comment by renmengyuan** [comment]
> @vchoutas sorry, that means that the female or male model do not work with this code? only the neutral model works? thanks

Any updates on this？
